script: "ruby test/test.rb"

branches:
  only:
    - master

rvm:
  - "1.8.7"
  - "1.9.3"
  - "2.0.0"
  - "jruby-18mode"
  - "jruby-19mode"

before_install:
  - gem update --system 2.1.11
  - gem --version