version: 2.1
jobs:
  default: &default
    docker:
      - image: cimg/ruby:2.7
    steps:
      - checkout
      - run: bundle check || bundle install
      - run:
          command: bundle exec rake
      - store_test_results:
          path: test-results
  test-2-5:
    <<: *default
    docker:
      - image: cimg/ruby:2.5
    steps:
      - checkout
      - attach_workspace:
          at: ~/repo/tmp
      - run:
          name:  Download cc-test-reporter
          command: |
            mkdir -p tmp/
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./tmp/cc-test-reporter
            chmod +x ./tmp/cc-test-reporter
      - run: bundle check || bundle install
      - run:
          command: |
            bundle exec rake
            ./tmp/cc-test-reporter format-coverage -t simplecov -o tmp/codeclimate.json coverage/.resultset.json
      - store_test_results:
          path: test-results
      - persist_to_workspace:
          root: tmp
          paths:
            - codeclimate.json
            - cc-test-reporter
  test-2-6:
    <<: *default
    docker:
      - image: cimg/ruby:2.6
  test-3-0:
    <<: *default
    docker:
      - image: circleci/ruby:3.0
  test-latest:
    <<: *default
    docker:
      - image: circleci/ruby:latest
  upload-coverage:
    <<: *default
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: ~/repo/tmp
      - run:
          name: Upload coverage results to Code Climate
          command: "./tmp/cc-test-reporter upload-coverage -i ./tmp/codeclimate.json"
workflows:
  version: 2
  tests:
    jobs:
      - default
      - test-2-5
      - test-2-6
      - test-3-0
      - test-latest
      - upload-coverage:
          requires:
            - test-2-5
