version: 2.1
orbs:
  qlty: qltysh/qlty-orb@0.1
jobs:
  default: &default
    docker:
      - image: cimg/ruby:3.3
    steps:
      - checkout
      - run: ruby --version && bundle check || bundle install
      - run:
          command: bundle exec rake
      - store_test_results:
          path: test-results
  test-3-2:
    <<: *default
    docker:
      - image: cimg/ruby:3.2
    steps:
      - checkout
      - attach_workspace:
          at: ~/repo/tmp
      - run: bundle check || bundle install
      - run:
          name: Run tests and generate coverage
          command: |
            # This triggers SimpleCov to generate a coverage.json file
            export CC_TEST_REPORTER_ID=CC_TEST_REPORTER_ID
            bundle exec rake RUBYOPT='--enable-frozen-string-literal --debug-frozen-string-literal'
            mkdir -p tmp/
            mv coverage/coverage.json tmp/coverage.json
      - store_test_results:
          path: test-results
      - persist_to_workspace:
          root: tmp
          paths:
            - coverage.json
  test-3-4:
    <<: *default
    docker:
      - image: cimg/ruby:3.4
  upload-coverage:
    <<: *default
    working_directory: ~/repo
    steps:
      - checkout
      - attach_workspace:
          at: ~/repo/tmp
      - qlty/coverage_publish:
          files: tmp/coverage.json
          strip_prefix: /home/circleci/project
workflows:
  version: 2
  tests:
    jobs:
      - default
      - test-3-2
      - test-3-4
      - upload-coverage:
          requires:
            - test-3-2
